name: API Build

on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v3.13.0
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Build project
      run: ./mvnw install
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: api
        path: /home/runner/work/oauth-playground-server/oauth-playground-server/target/oauth-playground-server-1.0.0-SNAPSHOT-runner.jar
